export const CLASS_EMAIL_MODAL_BACKDROP = "email-modal-backdrop";
export const CLASS_EMAIL_MODAL_CONTENT = "email-modal-content";
export const CLASS_EMAIL_MODAL_HEADER = "email-modal-header";
export const CLASS_EMAIL_MODAL_BODY = "email-modal-body";
export const CLASS_EMAIL_MODAL_FOOTER = "email-modal-footer";
export const CLASS_EMAIL_MODAL_CANCEL_BUTTON = "email-modal-cancel-button";
export const CLASS_EMAIL_MODAL_REQUEST_BUTTON = "email-modal-request-button";
export const CANCEL_BUTTON_TITLE = "ОТМЕНА";
export const REQUEST_BUTTON_TITLE = "ЗАПРОСИТЬ";
export const EMAIL_MODAL_TITLE = "Запросить токен";
export const CLASS_EMAIL_MODAL_TITLE = "email-modal-title"
export const EMAIL_MODAL_FORM_TITLE = "почта";
export const CLASS_EMAIL_MODAL_FORM = 'email-modal-form'
